/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AquariumsAndHobbyistsRouteImport } from './routes/aquariums-and-hobbyists'
import { Route as ArtemiaCystsIncubationGuideRouteImport } from './routes/artemia-cysts-incubation-guide'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CohoSalmonEggsRouteImport } from './routes/coho-salmon-eggs'
import { Route as ContactusRouteImport } from './routes/contactus'
import { Route as DecapsulatedArtemiaGuideRouteImport } from './routes/decapsulated-artemia-guide'
import { Route as DistanceSalesAgreementRouteImport } from './routes/distance-sales-agreement'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as HorecaSeafoodMiddleEastRouteImport } from './routes/horeca-seafood-middle-east'
import { Route as KvkkDisclosureTextRouteImport } from './routes/kvkk-disclosure-text'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegionalTradeMiddleEastEuropeRouteImport } from './routes/regional-trade-middle-east-europe'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as SalmonidOvaSolutionsRouteImport } from './routes/salmonid-ova-solutions'
import { Route as SeafoodExportRouteImport } from './routes/seafood-export'
import { Route as SeafoodExportFromTurkeyToEuropeRouteImport } from './routes/seafood-export-from-turkey-to-europe'
import { Route as ServicesSolutionsRouteImport } from './routes/services-solutions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountCustomsRouteImport } from './routes/account.customs'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiQuotesRouteImport } from './routes/api.quotes'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ApiAssetsOdooRouteImport } from './routes/api.assets.odoo'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthMeRouteImport } from './routes/api.auth.me'
import { Route as ApiAuthRegisterRouteImport } from './routes/api.auth.register'
import { Route as ApiPortalCustomsRouteImport } from './routes/api.portal.customs'
import { Route as ApiPortalOrdersRouteImport } from './routes/api.portal.orders'
import { Route as ApiPortalProfileRouteImport } from './routes/api.portal.profile'
import { Route as BlogCategoryIndexRouteImport } from './routes/blog.$category.index'
import { Route as BlogCategorySlugRouteImport } from './routes/blog.$category.$slug'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products.$category.index'
import { Route as ProductsCategorySlugRouteImport } from './routes/products.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AquariumsAndHobbyistsRoute = AquariumsAndHobbyistsRouteImport.update({
  id: '/aquariums-and-hobbyists',
  path: '/aquariums-and-hobbyists',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtemiaCystsIncubationGuideRoute =
  ArtemiaCystsIncubationGuideRouteImport.update({
    id: '/artemia-cysts-incubation-guide',
    path: '/artemia-cysts-incubation-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CohoSalmonEggsRoute = CohoSalmonEggsRouteImport.update({
  id: '/coho-salmon-eggs',
  path: '/coho-salmon-eggs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactusRoute = ContactusRouteImport.update({
  id: '/contactus',
  path: '/contactus',
  getParentRoute: () => rootRouteImport,
} as any)
const DecapsulatedArtemiaGuideRoute =
  DecapsulatedArtemiaGuideRouteImport.update({
    id: '/decapsulated-artemia-guide',
    path: '/decapsulated-artemia-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const DistanceSalesAgreementRoute = DistanceSalesAgreementRouteImport.update({
  id: '/distance-sales-agreement',
  path: '/distance-sales-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const HorecaSeafoodMiddleEastRoute = HorecaSeafoodMiddleEastRouteImport.update({
  id: '/horeca-seafood-middle-east',
  path: '/horeca-seafood-middle-east',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkDisclosureTextRoute = KvkkDisclosureTextRouteImport.update({
  id: '/kvkk-disclosure-text',
  path: '/kvkk-disclosure-text',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalTradeMiddleEastEuropeRoute =
  RegionalTradeMiddleEastEuropeRouteImport.update({
    id: '/regional-trade-middle-east-europe',
    path: '/regional-trade-middle-east-europe',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SalmonidOvaSolutionsRoute = SalmonidOvaSolutionsRouteImport.update({
  id: '/salmonid-ova-solutions',
  path: '/salmonid-ova-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SeafoodExportRoute = SeafoodExportRouteImport.update({
  id: '/seafood-export',
  path: '/seafood-export',
  getParentRoute: () => rootRouteImport,
} as any)
const SeafoodExportFromTurkeyToEuropeRoute =
  SeafoodExportFromTurkeyToEuropeRouteImport.update({
    id: '/seafood-export-from-turkey-to-europe',
    path: '/seafood-export-from-turkey-to-europe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSolutionsRoute = ServicesSolutionsRouteImport.update({
  id: '/services-solutions',
  path: '/services-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountCustomsRoute = AccountCustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotesRoute = ApiQuotesRouteImport.update({
  id: '/api/quotes',
  path: '/api/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsOdooRoute = ApiAssetsOdooRouteImport.update({
  id: '/api/assets/odoo',
  path: '/api/assets/odoo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalCustomsRoute = ApiPortalCustomsRouteImport.update({
  id: '/api/portal/customs',
  path: '/api/portal/customs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalOrdersRoute = ApiPortalOrdersRouteImport.update({
  id: '/api/portal/orders',
  path: '/api/portal/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalProfileRoute = ApiPortalProfileRouteImport.update({
  id: '/api/portal/profile',
  path: '/api/portal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryIndexRoute = BlogCategoryIndexRouteImport.update({
  id: '/blog/$category/',
  path: '/blog/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/$category/$slug',
  path: '/blog/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/$category/',
  path: '/products/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: '/products/$category/$slug',
  path: '/products/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/aquariums-and-hobbyists': typeof AquariumsAndHobbyistsRoute
  '/artemia-cysts-incubation-guide': typeof ArtemiaCystsIncubationGuideRoute
  '/cart': typeof CartRoute
  '/coho-salmon-eggs': typeof CohoSalmonEggsRoute
  '/contactus': typeof ContactusRoute
  '/decapsulated-artemia-guide': typeof DecapsulatedArtemiaGuideRoute
  '/distance-sales-agreement': typeof DistanceSalesAgreementRoute
  '/faqs': typeof FaqsRoute
  '/horeca-seafood-middle-east': typeof HorecaSeafoodMiddleEastRoute
  '/kvkk-disclosure-text': typeof KvkkDisclosureTextRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/regional-trade-middle-east-europe': typeof RegionalTradeMiddleEastEuropeRoute
  '/register': typeof RegisterRoute
  '/request-quote': typeof RequestQuoteRoute
  '/salmonid-ova-solutions': typeof SalmonidOvaSolutionsRoute
  '/seafood-export': typeof SeafoodExportRoute
  '/seafood-export-from-turkey-to-europe': typeof SeafoodExportFromTurkeyToEuropeRoute
  '/services-solutions': typeof ServicesSolutionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account/customs': typeof AccountCustomsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/assets/odoo': typeof ApiAssetsOdooRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/portal/customs': typeof ApiPortalCustomsRoute
  '/api/portal/orders': typeof ApiPortalOrdersRoute
  '/api/portal/profile': typeof ApiPortalProfileRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/products/$category/$slug': typeof ProductsCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/aquariums-and-hobbyists': typeof AquariumsAndHobbyistsRoute
  '/artemia-cysts-incubation-guide': typeof ArtemiaCystsIncubationGuideRoute
  '/cart': typeof CartRoute
  '/coho-salmon-eggs': typeof CohoSalmonEggsRoute
  '/contactus': typeof ContactusRoute
  '/decapsulated-artemia-guide': typeof DecapsulatedArtemiaGuideRoute
  '/distance-sales-agreement': typeof DistanceSalesAgreementRoute
  '/faqs': typeof FaqsRoute
  '/horeca-seafood-middle-east': typeof HorecaSeafoodMiddleEastRoute
  '/kvkk-disclosure-text': typeof KvkkDisclosureTextRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/regional-trade-middle-east-europe': typeof RegionalTradeMiddleEastEuropeRoute
  '/register': typeof RegisterRoute
  '/request-quote': typeof RequestQuoteRoute
  '/salmonid-ova-solutions': typeof SalmonidOvaSolutionsRoute
  '/seafood-export': typeof SeafoodExportRoute
  '/seafood-export-from-turkey-to-europe': typeof SeafoodExportFromTurkeyToEuropeRoute
  '/services-solutions': typeof ServicesSolutionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account/customs': typeof AccountCustomsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/account': typeof AccountIndexRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/api/assets/odoo': typeof ApiAssetsOdooRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/portal/customs': typeof ApiPortalCustomsRoute
  '/api/portal/orders': typeof ApiPortalOrdersRoute
  '/api/portal/profile': typeof ApiPortalProfileRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/products/$category/$slug': typeof ProductsCategorySlugRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
  '/products/$category': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRouteWithChildren
  '/aquariums-and-hobbyists': typeof AquariumsAndHobbyistsRoute
  '/artemia-cysts-incubation-guide': typeof ArtemiaCystsIncubationGuideRoute
  '/cart': typeof CartRoute
  '/coho-salmon-eggs': typeof CohoSalmonEggsRoute
  '/contactus': typeof ContactusRoute
  '/decapsulated-artemia-guide': typeof DecapsulatedArtemiaGuideRoute
  '/distance-sales-agreement': typeof DistanceSalesAgreementRoute
  '/faqs': typeof FaqsRoute
  '/horeca-seafood-middle-east': typeof HorecaSeafoodMiddleEastRoute
  '/kvkk-disclosure-text': typeof KvkkDisclosureTextRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/regional-trade-middle-east-europe': typeof RegionalTradeMiddleEastEuropeRoute
  '/register': typeof RegisterRoute
  '/request-quote': typeof RequestQuoteRoute
  '/salmonid-ova-solutions': typeof SalmonidOvaSolutionsRoute
  '/seafood-export': typeof SeafoodExportRoute
  '/seafood-export-from-turkey-to-europe': typeof SeafoodExportFromTurkeyToEuropeRoute
  '/services-solutions': typeof ServicesSolutionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/account/customs': typeof AccountCustomsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/quotes': typeof ApiQuotesRoute
  '/account/': typeof AccountIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/api/assets/odoo': typeof ApiAssetsOdooRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/portal/customs': typeof ApiPortalCustomsRoute
  '/api/portal/orders': typeof ApiPortalOrdersRoute
  '/api/portal/profile': typeof ApiPortalProfileRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/products/$category/$slug': typeof ProductsCategorySlugRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/aquariums-and-hobbyists'
    | '/artemia-cysts-incubation-guide'
    | '/cart'
    | '/coho-salmon-eggs'
    | '/contactus'
    | '/decapsulated-artemia-guide'
    | '/distance-sales-agreement'
    | '/faqs'
    | '/horeca-seafood-middle-east'
    | '/kvkk-disclosure-text'
    | '/login'
    | '/panel'
    | '/privacy'
    | '/projects'
    | '/regional-trade-middle-east-europe'
    | '/register'
    | '/request-quote'
    | '/salmonid-ova-solutions'
    | '/seafood-export'
    | '/seafood-export-from-turkey-to-europe'
    | '/services-solutions'
    | '/sitemap.xml'
    | '/terms'
    | '/account/customs'
    | '/account/orders'
    | '/account/profile'
    | '/api/health'
    | '/api/quotes'
    | '/account/'
    | '/blog/'
    | '/products/'
    | '/api/assets/odoo'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/portal/customs'
    | '/api/portal/orders'
    | '/api/portal/profile'
    | '/blog/$category/$slug'
    | '/products/$category/$slug'
    | '/blog/$category/'
    | '/products/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/aquariums-and-hobbyists'
    | '/artemia-cysts-incubation-guide'
    | '/cart'
    | '/coho-salmon-eggs'
    | '/contactus'
    | '/decapsulated-artemia-guide'
    | '/distance-sales-agreement'
    | '/faqs'
    | '/horeca-seafood-middle-east'
    | '/kvkk-disclosure-text'
    | '/login'
    | '/panel'
    | '/privacy'
    | '/projects'
    | '/regional-trade-middle-east-europe'
    | '/register'
    | '/request-quote'
    | '/salmonid-ova-solutions'
    | '/seafood-export'
    | '/seafood-export-from-turkey-to-europe'
    | '/services-solutions'
    | '/sitemap.xml'
    | '/terms'
    | '/account/customs'
    | '/account/orders'
    | '/account/profile'
    | '/api/health'
    | '/api/quotes'
    | '/account'
    | '/blog'
    | '/products'
    | '/api/assets/odoo'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/portal/customs'
    | '/api/portal/orders'
    | '/api/portal/profile'
    | '/blog/$category/$slug'
    | '/products/$category/$slug'
    | '/blog/$category'
    | '/products/$category'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/aquariums-and-hobbyists'
    | '/artemia-cysts-incubation-guide'
    | '/cart'
    | '/coho-salmon-eggs'
    | '/contactus'
    | '/decapsulated-artemia-guide'
    | '/distance-sales-agreement'
    | '/faqs'
    | '/horeca-seafood-middle-east'
    | '/kvkk-disclosure-text'
    | '/login'
    | '/panel'
    | '/privacy'
    | '/projects'
    | '/regional-trade-middle-east-europe'
    | '/register'
    | '/request-quote'
    | '/salmonid-ova-solutions'
    | '/seafood-export'
    | '/seafood-export-from-turkey-to-europe'
    | '/services-solutions'
    | '/sitemap.xml'
    | '/terms'
    | '/account/customs'
    | '/account/orders'
    | '/account/profile'
    | '/api/health'
    | '/api/quotes'
    | '/account/'
    | '/blog/'
    | '/products/'
    | '/api/assets/odoo'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/portal/customs'
    | '/api/portal/orders'
    | '/api/portal/profile'
    | '/blog/$category/$slug'
    | '/products/$category/$slug'
    | '/blog/$category/'
    | '/products/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRouteWithChildren
  AquariumsAndHobbyistsRoute: typeof AquariumsAndHobbyistsRoute
  ArtemiaCystsIncubationGuideRoute: typeof ArtemiaCystsIncubationGuideRoute
  CartRoute: typeof CartRoute
  CohoSalmonEggsRoute: typeof CohoSalmonEggsRoute
  ContactusRoute: typeof ContactusRoute
  DecapsulatedArtemiaGuideRoute: typeof DecapsulatedArtemiaGuideRoute
  DistanceSalesAgreementRoute: typeof DistanceSalesAgreementRoute
  FaqsRoute: typeof FaqsRoute
  HorecaSeafoodMiddleEastRoute: typeof HorecaSeafoodMiddleEastRoute
  KvkkDisclosureTextRoute: typeof KvkkDisclosureTextRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  RegionalTradeMiddleEastEuropeRoute: typeof RegionalTradeMiddleEastEuropeRoute
  RegisterRoute: typeof RegisterRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  SalmonidOvaSolutionsRoute: typeof SalmonidOvaSolutionsRoute
  SeafoodExportRoute: typeof SeafoodExportRoute
  SeafoodExportFromTurkeyToEuropeRoute: typeof SeafoodExportFromTurkeyToEuropeRoute
  ServicesSolutionsRoute: typeof ServicesSolutionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiQuotesRoute: typeof ApiQuotesRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiAssetsOdooRoute: typeof ApiAssetsOdooRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiPortalCustomsRoute: typeof ApiPortalCustomsRoute
  ApiPortalOrdersRoute: typeof ApiPortalOrdersRoute
  ApiPortalProfileRoute: typeof ApiPortalProfileRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRoute
  BlogCategoryIndexRoute: typeof BlogCategoryIndexRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aquariums-and-hobbyists': {
      id: '/aquariums-and-hobbyists'
      path: '/aquariums-and-hobbyists'
      fullPath: '/aquariums-and-hobbyists'
      preLoaderRoute: typeof AquariumsAndHobbyistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artemia-cysts-incubation-guide': {
      id: '/artemia-cysts-incubation-guide'
      path: '/artemia-cysts-incubation-guide'
      fullPath: '/artemia-cysts-incubation-guide'
      preLoaderRoute: typeof ArtemiaCystsIncubationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coho-salmon-eggs': {
      id: '/coho-salmon-eggs'
      path: '/coho-salmon-eggs'
      fullPath: '/coho-salmon-eggs'
      preLoaderRoute: typeof CohoSalmonEggsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactus': {
      id: '/contactus'
      path: '/contactus'
      fullPath: '/contactus'
      preLoaderRoute: typeof ContactusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decapsulated-artemia-guide': {
      id: '/decapsulated-artemia-guide'
      path: '/decapsulated-artemia-guide'
      fullPath: '/decapsulated-artemia-guide'
      preLoaderRoute: typeof DecapsulatedArtemiaGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distance-sales-agreement': {
      id: '/distance-sales-agreement'
      path: '/distance-sales-agreement'
      fullPath: '/distance-sales-agreement'
      preLoaderRoute: typeof DistanceSalesAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horeca-seafood-middle-east': {
      id: '/horeca-seafood-middle-east'
      path: '/horeca-seafood-middle-east'
      fullPath: '/horeca-seafood-middle-east'
      preLoaderRoute: typeof HorecaSeafoodMiddleEastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk-disclosure-text': {
      id: '/kvkk-disclosure-text'
      path: '/kvkk-disclosure-text'
      fullPath: '/kvkk-disclosure-text'
      preLoaderRoute: typeof KvkkDisclosureTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional-trade-middle-east-europe': {
      id: '/regional-trade-middle-east-europe'
      path: '/regional-trade-middle-east-europe'
      fullPath: '/regional-trade-middle-east-europe'
      preLoaderRoute: typeof RegionalTradeMiddleEastEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salmonid-ova-solutions': {
      id: '/salmonid-ova-solutions'
      path: '/salmonid-ova-solutions'
      fullPath: '/salmonid-ova-solutions'
      preLoaderRoute: typeof SalmonidOvaSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seafood-export': {
      id: '/seafood-export'
      path: '/seafood-export'
      fullPath: '/seafood-export'
      preLoaderRoute: typeof SeafoodExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seafood-export-from-turkey-to-europe': {
      id: '/seafood-export-from-turkey-to-europe'
      path: '/seafood-export-from-turkey-to-europe'
      fullPath: '/seafood-export-from-turkey-to-europe'
      preLoaderRoute: typeof SeafoodExportFromTurkeyToEuropeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-solutions': {
      id: '/services-solutions'
      path: '/services-solutions'
      fullPath: '/services-solutions'
      preLoaderRoute: typeof ServicesSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/customs': {
      id: '/account/customs'
      path: '/customs'
      fullPath: '/account/customs'
      preLoaderRoute: typeof AccountCustomsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotes': {
      id: '/api/quotes'
      path: '/api/quotes'
      fullPath: '/api/quotes'
      preLoaderRoute: typeof ApiQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/odoo': {
      id: '/api/assets/odoo'
      path: '/api/assets/odoo'
      fullPath: '/api/assets/odoo'
      preLoaderRoute: typeof ApiAssetsOdooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/customs': {
      id: '/api/portal/customs'
      path: '/api/portal/customs'
      fullPath: '/api/portal/customs'
      preLoaderRoute: typeof ApiPortalCustomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/orders': {
      id: '/api/portal/orders'
      path: '/api/portal/orders'
      fullPath: '/api/portal/orders'
      preLoaderRoute: typeof ApiPortalOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/profile': {
      id: '/api/portal/profile'
      path: '/api/portal/profile'
      fullPath: '/api/portal/profile'
      preLoaderRoute: typeof ApiPortalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/': {
      id: '/blog/$category/'
      path: '/blog/$category'
      fullPath: '/blog/$category/'
      preLoaderRoute: typeof BlogCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/$slug': {
      id: '/blog/$category/$slug'
      path: '/blog/$category/$slug'
      fullPath: '/blog/$category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/': {
      id: '/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/$slug': {
      id: '/products/$category/$slug'
      path: '/products/$category/$slug'
      fullPath: '/products/$category/$slug'
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountCustomsRoute: typeof AccountCustomsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountCustomsRoute: AccountCustomsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRouteWithChildren,
  AquariumsAndHobbyistsRoute: AquariumsAndHobbyistsRoute,
  ArtemiaCystsIncubationGuideRoute: ArtemiaCystsIncubationGuideRoute,
  CartRoute: CartRoute,
  CohoSalmonEggsRoute: CohoSalmonEggsRoute,
  ContactusRoute: ContactusRoute,
  DecapsulatedArtemiaGuideRoute: DecapsulatedArtemiaGuideRoute,
  DistanceSalesAgreementRoute: DistanceSalesAgreementRoute,
  FaqsRoute: FaqsRoute,
  HorecaSeafoodMiddleEastRoute: HorecaSeafoodMiddleEastRoute,
  KvkkDisclosureTextRoute: KvkkDisclosureTextRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  RegionalTradeMiddleEastEuropeRoute: RegionalTradeMiddleEastEuropeRoute,
  RegisterRoute: RegisterRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  SalmonidOvaSolutionsRoute: SalmonidOvaSolutionsRoute,
  SeafoodExportRoute: SeafoodExportRoute,
  SeafoodExportFromTurkeyToEuropeRoute: SeafoodExportFromTurkeyToEuropeRoute,
  ServicesSolutionsRoute: ServicesSolutionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiQuotesRoute: ApiQuotesRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiAssetsOdooRoute: ApiAssetsOdooRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiPortalCustomsRoute: ApiPortalCustomsRoute,
  ApiPortalOrdersRoute: ApiPortalOrdersRoute,
  ApiPortalProfileRoute: ApiPortalProfileRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  ProductsCategorySlugRoute: ProductsCategorySlugRoute,
  BlogCategoryIndexRoute: BlogCategoryIndexRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
